### ISSUE TITLE
Suggestion: MIDI Conversion

### ISSUE THREAD

**Issue by NataliaShmueli** [sdercolin/utaformatix3#142]
Would it be possible to convert to standard format .mid in the future as well? Thank you!

**Comment by sdercolin** [comment]
Could I ask what it's for? I think most editor have MIDI import/export features

**Comment by NataliaShmueli** [comment]
Corpus-related works, mostly! If not, that's totally fine.

**Comment by oxygen-dioxide** [comment]
> Could I ask what it's for? I think most editors have MIDI import/export features.

Though editors have standard .mid file import/export features, they may not support all the features that midi file have, like lyric encoding. Besides, some editor even can't export midi, such as Deepvocal

**Comment by sdercolin** [comment]
Yes I think it will be nice if we have it. If anyone would like to help implement this, I can support.
We already have MIDI parsing library used for the VOCALOID MIDI format.

**Comment by sdercolin** [comment]
Released
