### ISSUE TITLE
suggestion: .tssln (voisona file) import support

### ISSUE THREAD

**Issue by blackhomotoadshoe** [sdercolin/utaformatix3#149]
voisona lets you import a .ccs but when saving a file the only option is .tssln which isn't supported by cevio (and anything else obviously). there aren't much files of this type that people distribute yet but i'd still appreciate if it was added 🙏🏼

**Comment by SoulMelody** [comment]
tssln is a file format based on ValueTree, which originates from the JUCE C++ library. Here is a simple parsing example in Python: [.](https://github.com/SoulMelody/LibreSVIP/blob/main/tests/test_plugin.py#L61)

**Comment by sdercolin** [comment]
Sorry I don't have enough time to work one this recently, but I would like to support around usages of Kotlin grammar and the codebase, if anyone would like to lead the development of this feature.
