### ISSUE TITLE
.acep format import support

### ISSUE THREAD

**Issue by iruhamu03** [sdercolin/utaformatix3#152]
Is it possible to add .acep/ACE Studio project import support?

**Comment by sdercolin** [comment]
Isn't it encrypted? Also I think ACE studio supports UFDATA.

**Comment by iruhamu03** [comment]
I don't know, I'm never trying to digging into the file structure
Anyway, I request this feature because I have some .acep files and I want to export them to MIDI files. But since ACE Studio now requires subscription, I can't do it without subscribing their plans

**Comment by sdercolin** [comment]
Sorry about that.
We cannot add features that may be against the terms of service of ACE.
