### ISSUE TITLE
pitchbend errors converting from a ustx file (openutau) to vsqx (vocaloid4, however using piapro studio v4x)

### ISSUE THREAD

**Issue by Liniaxx** [sdercolin/utaformatix3#179]
so a bit of context - i do all of my tuning through openutau. i can't tune easily in piapro, and thus prefer tuning in openutau. i also have very crazy tuning, to describe it in a few words. think tuning of the likes of rishie-p or pigeonandruko, maybe a little simpler but among those levels.

with the context out of the way, here is where things get difficult. when i try to put my tuned ustx through utaformatix (with the convert pitches setting on), this weird stuff happens where the pitch is altered and goes off-key, as seen in the image comparison below. i don't know why it does this and it's really annoying, and the only guess that i have is that it's my tuning style, which not only do i NOT want to change at all, i can't figure out how to simplify it to my liking anyways, as i always go back to the crazier style. i can't figure out how to make it so it converts the crazy pitches correctly and makes them sing in key. can somebody assist me with this? this is really bugging me and will make things like making my own songs and stuff really hard if i can't fix it.

![weird utaformatix crazy tuning bug](https://github.com/user-attachments/assets/57b34835-3c93-4159-a8f3-f5e8a3dcaf9e)

**Comment by sdercolin** [comment]
Specially, if the converted pitch data contains pitch transition (e.g. ust), you can try adjusting pitch transition settings (or use pitch-snap/robot mode) in the target editor to avoid overlay.

↑ from the FAQ

it looks like you didn't remove the default pitch transition in piapro, so what you get is a combination of the converted pitch parameters and the default pitch parameters.
In VOCALOID 4 there is a Pitch Snap mode, and you should always turn it on if you want to hear exactly the same pitch as your PIT parameters. I'm not sure what's the name of a similar setting in Piapro so please look for it

**Comment by Liniaxx** [comment]
@sdercolin 
i've done that and found it's not an issue with the pitch snap mode but rather the actual pitchbends themselves. the pitchbends are somehow, someway, being converted through incorrectly and it messes with the tuning. i've done this with other ustx's as well, and most of them have the same issue. it's also not limited to piapro - i converted it to an svp and opened it in synthv, and it had the same issue, again, it's the pitchbends themself, which is why i bring up this issue here. using the auto-pitch works for most notes but not these weird broken pitch ones. (note that i know the pitch snap will fix issues with the combined pitches, and used it when i noticed this bug!)

and here's the actual display of the pitchbend parameters compared to the pitchline on the notes i used in the example, so you can see it's the bends itself being taken in oddly by the program

![image](https://github.com/user-attachments/assets/a5f54f72-4e1e-4d49-9c59-02edf0e0c9e0)
![image](https://github.com/user-attachments/assets/d37a7899-ce63-4309-86ce-1d7a26e9e69c)
![image](https://github.com/user-attachments/assets/d77f446c-dc87-46c2-955a-a85b8814529a)

**Comment by sdercolin** [comment]
Could you please send one of the ustx to me? I will have a look
-> sder.colin@gmail.com

**Comment by sdercolin** [comment]
<img width="1766" alt="截屏2024-07-15 16 23 52" src="https://github.com/user-attachments/assets/a886da7f-ecd9-4695-bfa2-4d4142620025">
BTW I tried to create a similar style ustx and convert it to svp (with transitions/vibrato removed) and it looks proper, so it might be indeed some special data in your projects

**Comment by sdercolin** [comment]
![QQ_1721028539097](https://github.com/user-attachments/assets/8c30457f-db8e-4d8a-8d96-0fa854f86ceb)
BTW I created a similar style ustx and converted it to svp (with transitions/vibrato removed) and it looks proper.
So it might indeed be some special data in your case 🤔

**Comment by Liniaxx** [comment]
@sdercolin ah, i see, i was wondering if it a thing on my end or not. probably the crazy tuning stressing the website and it freaks out lol, and as for sending the ustx, i'll be sending it over asap so you can try and see if it's something that's only happening on my end! look for an email from liniaxxskits@gmail.com ^^

**Comment by sdercolin** [comment]
![QQ_1721102406655](https://github.com/user-attachments/assets/5059195e-97fa-4c15-a0f2-c5c771cba42d)
![QQ_1721102810120](https://github.com/user-attachments/assets/cf7f18b4-6ad5-41ee-adf7-b66c2ff24024)

@Liniaxx I converted your ustx to SVP and VSQX and it looks as expected.

The screenshots are taken with OpenUtau + VOCALOID 5 (with Robot Voice turned on max).
Please try with the [converted vsqx](https://drive.google.com/file/d/140rpGGgcL4AMA5wa1XIYuMZ7f76qwhth/view?usp=sharing) and share more info about your issues.
(only you can open this link)

**Comment by Liniaxx** [comment]
@sdercolin huh, odd, looks to be a worse issue on my end through raw ustx to vsqx conversion? and for the reconverted vsqx you sent, it seems to be fine for the most part and converted much better, however i did notice these skimming through it at new areas now:

![image](https://github.com/user-attachments/assets/e648f9c4-77b3-4517-812c-4f188472759d)
![image](https://github.com/user-attachments/assets/86ba396d-e5e7-4728-8971-451ace731029)
![image](https://github.com/user-attachments/assets/3ed8fbeb-d90d-4dd1-8f8c-0dd5b578f348)

it is definitely less severe converting it this way! i believe i also mentioned that i also tried svp conversion and got similar results as this, more like a mix of these issues honestly. but it did make a difference converting that way!

**Comment by sdercolin** [comment]
@Liniaxx Thank you for your detailed report. I think I have found the issue and fixed it.
The condition of the issue is: there are some pitch points that are too close to each other.
![QQ_1721552433480](https://github.com/user-attachments/assets/b6557488-9bb7-4346-a698-cb44bd8defb8)
e.g. in this note, there are points that have the exactly same "X" position, so they are merged averagely in the following resampling process.

Please check a beta deployed version 3.22.1 here to see if there is any issue during UTAU/OpenUtau pitch conversion.
https://sdercolin.github.io/utaformatix3/beta/
Also, even if this issue is fixed, the change might bring other issues, so it would be very helpful if you could try with multiple UST/USTX files, if possible, with different tuning styles 🙇

**Comment by Liniaxx** [comment]
@sdercolin it works perfectly now! i've tried it with three usts - the one i was using before (deep sea girl), an old and horrid ustx i made of bug with much simpler tuning, and an untuned ust of white happy i found by akem, and all of them seem to be working perfectly fine! the issue seems to be fixed now! tysm ^^

**Comment by sdercolin** [comment]
@Liniaxx Thank you for the confirmation.
I have adjusted the algorithm again, so could you please test again with those project files?

**Comment by Liniaxx** [comment]
@sdercolin tried on each ustx and ust, even threw in another one i tuned crazily, and everything is working perfectly now from the looks of it!! tysm, i can go properly crazy tune the yellow ones as crazy as i want now ^^
