### ISSUE TITLE
Standard MIDI with only 1 track is treated as empty

### ISSUE THREAD

**Issue by sevenc-nanashi** [sdercolin/utaformatix3#182]
Standard MIDI file (including SMF type 0) with only 1 track is treated as empty.
https://github.com/sdercolin/utaformatix3/blob/17de7cbe9fa0a0fca63e18f27b563a2f07bf85cc/core/src/main/kotlin/core/io/StandardMid.kt#L39

Idea: Parse all tracks first, and delete the first track if it's empty (to remove a track which is used only for including things like tempos)

**Comment by colin-weng-s** [comment]
What doesn't it mean? The first track might include notes if there is only one track?

**Comment by sdercolin** [comment]
What doesn't it mean? The first track might include notes if there is only one track?

**Comment by sevenc-nanashi** [comment]
Yes, especially SMF type 0.
For example: https://x.com/okep_s/status/1819695499399835974?s=46
