### ISSUE TITLE
The lyric “-” couldn't be converted into “ー” when converting into .ccs files.

### ISSUE THREAD

**Issue by uselessbug** [sdercolin/utaformatix3#45]
"-" should be converted into "ー" or it won't be recognized by CeVIO

**Comment by sdercolin** [comment]
Thanks for the report! Let me consider how to do it...

**Comment by sdercolin** [comment]
@uselessbug The fix is deployed to beta: https://salty-citadel-72030.herokuapp.com
Please have a try..

**Comment by uselessbug** [comment]
> 
> 
> @uselessbug The fix is deployed to beta: https://salty-citadel-72030.herokuapp.com
> Please have a try..

It worked!!
![image](https://user-images.githubusercontent.com/61285640/107461490-1154c780-6b95-11eb-9e62-399375569c09.png)
