### ISSUE TITLE
utaformatix离线版

### ISSUE THREAD

**Issue by oxygen-dioxide** [sdercolin/utaformatix3#53]
我用electron打包了一个离线的utaformatix：https://github.com/oxygen-dioxide/utaformatix-electron
你们可以在“常见问题解答”页面提供一个链接。

另外，edge浏览器可以将网站变成应用。

**Comment by sdercolin** [comment]
Thank you for your contribution, however currently we have no plan for supporting a dedicated version of UtaFormatix as an offline app. (we would like people use online version)
Since this is not an issue, I will close it.
