### ISSUE TITLE
No sound when converting Kana to Romaji for DeepVocal

### ISSUE THREAD

**Issue by Necklaces** [sdercolin/utaformatix3#57]
I'm no expert in neither Japanese nor DeepVocal, but when converting files (mainly musicxml) using Kana to DeepVocal a couple of lyrics don't play any sound for me, here are some examples:

These are canonically correct romaji, but play no sound at all:
- ひ turns into hi, it seems DV uses "hyi" 
- り turns into ri, it seems DV uses "ryi"
- ん turns into n, it seems DV uses "N" (uppercase)
- は turns into ha, it seems DV uses "haa"
- み turns into mi, it seems DV uses "myi"
- ほ turns into ho, it seems DV uses "hoo"
- に turns into ni, it seems DV uses "nyi"

There are probably more, but these are the ones I've found so far. No idea why it is like this, maybe it's my voicebank?

Thanks for making this, by the way!

**Comment by shine5402** [comment]
Hi there, thanks for your feedback.
The mapping between kana lyrics and actual vb block symbol depends on the voicebank itself (or rather, dic file comes with the vb), and the actual symbol that voicebank uses is unknown and unpredictable to Utaformatix. Though you can use the "tab" trick to ask DeepVocal remap symbols for you. That is to say, double click the first note, and keep pressing "Tab" on the keyborad. DeepVocal will see it as you are inputting the lyrics again and remap symbols being used.

**Comment by Necklaces** [comment]
I see that solves that then, closing the issue. Unfortunately that Tab trick does not work for me, oh well.
